# Generated by Django 6.0.1 on 2026-02-03 06:27

import performance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentperformance',
            name='hours_studied',
            field=models.FloatField(validators=[performance.models.validate_hours_studied]),
        ),
        migrations.AlterField(
            model_name='studentperformance',
            name='performance_index',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentperformance',
            name='previous_scores',
            field=models.IntegerField(validators=[performance.models.validate_previous_scores]),
        ),
        migrations.AlterField(
            model_name='studentperformance',
            name='sample_papers',
            field=models.IntegerField(validators=[performance.models.validate_sample_papers]),
        ),
        migrations.AlterField(
            model_name='studentperformance',
            name='sleep_hours',
            field=models.FloatField(validators=[performance.models.validate_sleep_hours]),
        ),
    ]
